name: Static Code Analysis

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        php: [8.1]
        tdengine: [2.0.22.0]

    env:
      PHP_DOCKER_VERSION: ${{ matrix.php }}
      TDENGINE_VERSION: ${{ matrix.tdengine }}

    steps:
      - uses: actions/checkout@v2

      - name: prepare
        run: |
          cd .github
          docker-compose up -d php
          docker exec php composer update

      - name: Test
        run: docker exec php ./vendor/bin/phpstan analyse --memory-limit 1G
